<template>
  <div id="about">
    <h2>About Password Generator Website</h2>
    <p>With more and more online accounts available, and more and more individuals looking to exploit online accounts it is vital that your passwords are different for each account you have. This site provides a way of generating random passwords to suit this need. The code behind the site creates passwords to your requirements using a cryptographically secure random number generator assigning the values to letters, numbers, or symbols as appropriate. For a secure random password make a long password with letters, numbers, and symbols. If you don't have access to a password store application this site can also generate passwords made up of two or more randomly picked words and numbers.</p>
    <p>If you are in the business of uploading files to the web for users to download at a later date and need to provide those users reassurance, or regularly download files that come with checksums, then that is where our file integrity section comes into play. Knowing that the file you have downloaded is the genuine version, unaltered, is vital to prevent your systems from being exploited by malicious software. We don't currently have the capability to generate checksums on this site, but have provided instructions for you to generate them yourself offline, on both Windows and MacOS.</p>
    <p>No password generated by the site is stored anywhere on our servers, and this site uses HTTPS to protect the transmission of the password to you after generation. For further information on what we do and don't and our liabilities please check out our legal page. We are a UK-based website, with the servers hosting our files based in the USA.</p>
    <p>For the more technically minded our servers are running php 8 and the passwords are generated using the random_int() function as recommended by php.net for generating cryptographically secure random numbers.</p>
    <p>If you want to get in touch with us then please click on the Twitter icon at the bottom of this page and tweet us.</p>
  </div>
</template>

<style scoped>
  #about {
    width: 1080px;
    margin: 100px auto;
  }
  h2 {
    margin-bottom: 10px;
  }
  p {
    text-align: justify;
    margin: 5px 0px;
  }
</style>
