<template>
    <div id="legal">
        <h2>Legal Information for Password Generator Website</h2>
        <p>Our terms of use our simple really. This website is for individuals or businesses to generate random passwords. No password generated by this website is stored by the owner of the site, and no data is harvested that may identify individual users of the website over and above the standard hosting company log files.</p>
        <p>On request we are happy to provide details of how the passwords have been generated. We make no assurance that passwords generated by this website are unbreakable, but assert that passwords are as randomly generated as is currently possible.</p>
        <p>This website makes use of cookies generated by google as part of their website analytics and advertising programs. We do not make any use of the data contained in cookies generated by us once you have left this site.</p>
        <p>Password Generator Website takes no responsibility for any loss of data or access to services as a result of passwords generated by this site. By clicking the Generate Password or Generate PIN buttons you accept the terms of use of this website.</p>
        <p>The following below website disclaimer sets out in full everything else not covered by the above statements.</p>
        <div id="disclaimer">
            <h3>Password Generator Website disclaimer</h3>
            <p>1. Introduction</p>
            <p class="tabOne">1.1 This disclaimer shall govern your use of our website.</p>
            <p class="tabOne">1.2 By using our website, you accept this disclaimer in full; accordingly, if you disagree with this disclaimer or any part of this disclaimer, you must not use our website.</p>
            <p>2. Credit</p>
            <p class="tabOne">2.1 This document was created using a template from SEQ Legal (http://www.seqlegal.com).</p>
            <p>3. Copyright notice</p>
            <p class="tabOne">3.1 Copyright (c) 2017 Password Generator Website.</p>
            <p class="tabOne">3.2 Subject to the express provisions of this disclaimer:</p>
            <p class="tabTwo">(a) we, together with our licensors, own and control all the copyright and other intellectual property rights in our website and the material on our website; and</p>
            <p class="tabTwo">(b) all the copyright and other intellectual property rights in our website and the material on our website are reserved.</p>
            <p>4. Licence to use website</p>
            <p class="tabOne">4.1 You may:</p>
            <p class="tabTwo">(a) view pages from our website in a web browser;</p>
            <p class="tabTwo">(b) download pages from our website for caching in a web browser; and</p>
            <p class="tabTwo">(c) print pages from our website, subject to the other provisions of this disclaimer.</p>
            <p class="tabTwo">4.2 Except as expressly permitted by Section 4.1 or the other provisions of this disclaimer, you must not download any material from our website or save any such material to your computer.</p>
            <p class="tabTwo">4.3 You may only use our website for the generation of Passwords or Personal Identification Numbers [PIN], and you must not use our website for any other purposes.</p>
            <p class="tabOne">4.4 Unless you own or control the relevant rights in the material, you must not:</p>
            <p class="tabTwo">(a) republish material from our website (including republication on another website);</p>
            <p class="tabTwo">(b) sell, rent or sub-license material from our website;</p>
            <p class="tabTwo">(c) show any material from our website in public;</p>
            <p class="tabTwo">(d) exploit material from our website for a commercial purpose; or</p>
            <p class="tabTwo">(e) redistribute material from our website.</p>
            <p class="tabTwo">4.5 We reserve the right to restrict access to areas of our website, or indeed our whole website, at our discretion; you must not circumvent or bypass, or attempt to circumvent or bypass, any access restriction measures on our website.</p>
            <p>5. Acceptable use</p>
            <p class="tabOne">5.1 You must not:</p>
            <p class="tabTwo">(a) use our website in any way or take any action that causes, or may cause, damage to the website or impairment of the performance, availability or accessibility of the website;</p>
            <p class="tabTwo">(b) use our website in any way that is unlawful, illegal, fraudulent or harmful, or in connection with any unlawful, illegal, fraudulent or harmful purpose or activity;</p>
            <p class="tabTwo">(d) use our website to copy, store, host, transmit, send, use, publish or distribute any material which consists of (or is linked to) any spyware, computer virus, Trojan horse, worm, keystroke logger, rootkit or other malicious computer software;</p>
            <p class="tabTwo">(e) conduct any systematic or automated data collection activities (including without limitation scraping, data mining, data extraction and data harvesting) on or in relation to our website without our express written consent;</p>
        </div>
    </div>
</template>

<script></script>

<style scoped>
  #legal {
    width: 1080px;
    margin: 100px auto;
  }

  #disclaimer {
    width: 100%;
    margin: 20px auto;
    padding: 40px;
    background-color: #e0e0e0e0;
    border-radius: 20px;
  }
  #disclaimer p {
    font-family: 'PT Mono',monospace;
    font-size: 10px;
    color: #000000;
  }
  .tabOne {
    text-indent: 20px;
  }
  .tabTwo {
    text-indent: 40px;
  }

  h2 {
    margin-bottom: 10px;
  } 
  
  p {
    text-align: justify;
    margin: 5px 0px;
  }
</style>